---
  - shell: dig @resolver1.opendns.com ANY myip.opendns.com +short
    register: public_ip_res
  - set_fact:
      public_ip={{public_ip_res.stdout}}
  - debug: msg="Public IP = {{public_ip}}"
  - template:
      src: env.j2
      dest: shaman.env.{{container_name}}.list
  - name: Pulling image
    shell: "docker pull {{docker_repository}}:{{docker_image}}"
    register: res
  - debug: msg="{{res.stdout}}"
  - name: Stop {{container_name}} container
    shell: "docker stop {{container_name}} || true"
    register: res
  - name: Remove {{container_name}} container
    shell: "docker rm {{container_name}} || true"
    register: res
  - debug: msg="{{res.stdout}}"    
  - name: Run {{container_name}} container
    shell: "docker run -d --net=host --name={{container_name}} --env-file ~/shaman.env.{{container_name}}.list --log-opt max-size=100m {{docker_repository}}:{{docker_image}}"
    register: res
  - debug: msg="{{res.stdout}}"
